name: ExampleUI
version: 1.0
api: 3.0.0
author: SaveConnectionPE
main: Example\Main

commands:
  example:
    description: "§7Öffnet die §9§lExampleUI§r§4!"

permissions:
  example.use:
    description: "Allow the player to open the ExampleUI!"
